"""Phase 1 validation: CustomGNFW profile vs XGPaint gold references.

Reference CSVs in reference/data/ are generated by reference/julia/gen_reference.jl
(XGPaint, analytic FlatLCDM, B=1.41).  Run directly:
    python tests/test_phase1.py
or under pytest.
"""
import os
import sys
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from jxpaint.cosmology import default_cosmology
from jxpaint.profiles.custom_gnfw import CustomGNFWPressureProfile

REFDIR = os.path.join(os.path.dirname(__file__), "..", "reference", "data")


def _load_csv(name):
    return np.genfromtxt(os.path.join(REFDIR, name), delimiter=",", names=True)


def _relerr(a, b):
    a = np.asarray(a, float); b = np.asarray(b, float)
    return np.abs(a - b) / np.maximum(np.abs(b), 1e-300)


def test_cosmology_geometry():
    """E(z), d_A, rho_crit, R500, theta500 vs XGPaint, rel err < 1e-6."""
    d = _load_csv("cosmo_geometry.csv")
    cz = default_cosmology()
    p = CustomGNFWPressureProfile()
    M, z = d["M_1e14"], d["z"]
    Ez = np.array([float(cz.E(zz)) for zz in z])
    dA = np.array([float(cz.angular_diameter_dist(zz)) for zz in z])
    rho = np.array([float(cz.rho_crit(zz)) for zz in z])
    R500 = np.array([float(p.r500c_Mpc(mm, zz, apply_bias=True)) for mm, zz in zip(M, z)])
    th500 = np.array([float(p.theta500(mm, zz)) for mm, zz in zip(M, z)])
    for name, mine, ref in [
        ("E", Ez, d["Ez"]), ("dA", dA, d["dA_Mpc"]),
        ("rho_crit", rho, d["rho_crit_kgm3"]),
        ("R500", R500, d["R500_Mpc"]), ("theta500", th500, d["theta500_rad"]),
    ]:
        e = _relerr(mine, ref).max()
        print(f"  cosmo {name:10s} max rel err = {e:.3e}")
        assert e < 1e-6, f"{name} rel err {e:.3e} >= 1e-6"


def test_shape_1d():
    """Projected shape F(x) vs XGPaint los_quadrature, rel err < 1e-5."""
    d = _load_csv("shape_1d.csv")
    p = CustomGNFWPressureProfile()
    Fmine = np.array(p.F(d["x"]))
    e = _relerr(Fmine, d["F"])
    print(f"  shape_1d F(x) max rel err = {e.max():.3e} at x={d['x'][e.argmax()]:.3e}")
    assert e.max() < 1e-5


def test_y_los_central():
    """y_los at tiny theta vs XGPaint compton_y central, rel err < 1e-5."""
    d = _load_csv("y0_arnaud.csv")
    p = CustomGNFWPressureProfile()
    ymine = np.array([float(p.y_los(1e-10, mm, zz))
                      for mm, zz in zip(d["M_1e14"], d["z"])])
    e = _relerr(ymine, d["y0_arnaud_center"])
    print(f"  y_los central max rel err = {e.max():.3e}")
    assert e.max() < 1e-5


def _load_scalars():
    vals = {}
    with open(os.path.join(REFDIR, "scalars.csv")) as f:
        next(f)
        for line in f:
            k, v = line.strip().split(",")
            vals[k] = float(v)
    return vals


def test_scalars():
    """Profile shape constants match XGPaint get_params."""
    vals = _load_scalars()
    p = CustomGNFWPressureProfile()
    assert abs(p.P0 - vals["P0"]) < 1e-12
    assert abs(p.alpha - vals["alpha"]) < 1e-12
    # XGPaint xc = 1/c500
    assert abs(1.0 / p.c500 - vals["xc"]) < 1e-12
    # XGPaint stores beta,gamma negated relative to hmfast convention
    assert abs(p.beta - (-vals["beta"])) < 1e-9
    assert abs(p.gamma - (-vals["gamma"])) < 1e-9
    print("  scalars OK")


def test_hmfast_equivalence():
    """y0_param/y0_arnaud arithmetic matches hmfast (fed hmfast's E, r500c), rel<1e-6.

    hmfast uses a slightly different (neutrino-inclusive emulator) cosmology, so we
    isolate the *profile formula* by passing hmfast's own E(z) and r500c into our
    expressions.  This verifies CustomGNFW == hmfast ParametricGNFWPressureProfile.
    """
    path = os.path.join(os.path.dirname(__file__), "..", "reference", "hmfast",
                        "hmfast_ref_hp.csv")
    d = np.genfromtxt(path, delimiter=",", names=True)
    p = CustomGNFWPressureProfile()
    M_1e14 = d["M500c_Msun"] / 1e14
    yp = np.array([float(p.y0_param_from_E(m, E)) for m, E in zip(M_1e14, d["Ez"])])
    ya = np.array([float(p.y0_arnaud_from_E_r(m, E, r))
                   for m, E, r in zip(M_1e14, d["Ez"], d["r500c_Mpc"])])
    ep = _relerr(yp, d["y0_param"]).max()
    ea = _relerr(ya, d["y0_orig"]).max()
    print(f"  hmfast y0_param max rel err = {ep:.3e}")
    print(f"  hmfast y0_orig  max rel err = {ea:.3e}")
    assert ep < 1e-6 and ea < 1e-6


def test_shape2d_beamed():
    """Bicubic beamed shape table vs cached XGPaint itp2d, rel err < 1e-4."""
    from jxpaint.profiles.shape_table import load_beamed_table
    bin_path = os.path.join(REFDIR, "beamed_table_coefs.f64")
    if not os.path.exists(bin_path):
        print("  SKIP: beamed_table_coefs.f64 not present")
        return
    t = load_beamed_table()
    d = _load_csv("shape2d_beamed.csv")
    mine = np.array(t.evaluate(d["logtheta"], d["logtheta500"]))
    e = _relerr(mine, d["yt"]).max()
    print(f"  shape2d beamed max rel err = {e:.3e} (N={len(d['yt'])})")
    assert e < 1e-4


if __name__ == "__main__":
    fails = 0
    for fn in [test_scalars, test_cosmology_geometry, test_shape_1d,
               test_y_los_central, test_hmfast_equivalence, test_shape2d_beamed]:
        try:
            print(f"[{fn.__name__}]")
            fn()
            print(f"  PASS")
        except AssertionError as e:
            fails += 1
            print(f"  FAIL: {e}")
    print("\n", "ALL PASS" if fails == 0 else f"{fails} FAILED")
    sys.exit(1 if fails else 0)
